pos_system/pos_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('products/', include('products.urls')),
    path('vendors/', include('vendor.urls')),
    path('purchases/', include('purchases.urls')),
    path('sales/', include('sales.urls')),
    path('customers/', include('customer.urls')),
    path('payments/', include('payments.urls')),
]

pos_system/sales/urls.py
from django.urls import path
from . import views

# sales/urls.py
app_name = 'sales'

urlpatterns = [
    path('', views.SalesListView.as_view(), name="sales_list_view"),
    path('create-sale-order/', views.SalesOrderFormView.as_view(), name='create_sales_order'),
    path('sales-items/<int:pk>/', views.SalesOrderItemsFormView.as_view(), name='create_sales_order_items'),
    path('sales-order-detail/<int:pk>/', views.SalesOrderDetailView.as_view(), name="sales_detail_view"),

    # API Endpoints
    path("api/product-by-barcode/", views.product_by_barcode, name="product_by_barcode"),

]

pos_system/sales/models.py
from django.db import models
from django.utils import timezone
from products.models import Product
from customer.models import Customer
from django.contrib.auth.models import User
import string, random
from decimal import Decimal

# Create your models here.

def generate_invoice_number():
    while True:
        alpnum = string.ascii_uppercase + string.digits
        end = ''.join(random.choices(alpnum, k=6))
        numbers = ''.join(random.choices(string.digits, k=6))
        invoice = f"INV-{numbers}-{end}"
        if not SalesOrder.objects.filter(invoice_number=invoice).exists():
            return invoice

def generate_order_id():
    prefix = "S-ORDER-"
    last_order = SalesOrder.objects.order_by("-id").first()

    if not last_order:
        new_num = 1
    else:
        last_id = last_order.order_id
        try:
            last_number = int(last_id.split("-")[-1])
            new_num = last_number + 1
        except (IndexError, ValueError):
            new_num = last_order.id + 1
    return f"{prefix}{new_num:03d}"

class SalesOrder(models.Model):
    STATUS_CHOICES = [
        ("unpaid", "Unpaid"),
        ("partial", "Partial"),
        ("paid", "Paid"),
    ]

    order_id = models.CharField(max_length=20, unique=True, default=generate_order_id)
    invoice_number = models.CharField(max_length=50, unique=True, default=generate_invoice_number)
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    sale_date = models.DateTimeField(default=timezone.now)

    subtotal = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    paid_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    remaining_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="unpaid")
    payment_method = models.CharField(max_length=20, default="Cash")  # Cash / Card / Credit
    notes = models.TextField(blank=True, null=True)

    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="created_sales_order")
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-sale_date']
        verbose_name = "Sales Order"
        verbose_name_plural = "Sales Orders"

    def __str__(self):
        return f"{self.order_id} - #{self.invoice_number}"

    @property
    def due_amount(self):
        """Return how much the customer still owes."""
        return max(self.total_amount - self.paid_amount, 0)
    
    def update_customer_balance(self):
        """Adjust customer's current balance after sale."""
        if self.customer:
            self.customer.current_balance += Decimal(self.total_amount)
            self.customer.save(update_fields=['current_balance'])




class SalesOrderItem(models.Model):
    sales_order = models.ForeignKey(SalesOrder, on_delete=models.CASCADE, related_name="sales_items")
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(default=1)
    sale_price = models.DecimalField(max_digits=10, decimal_places=2)
    line_total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.product.product_name} ({self.quantity})"

    def save(self, *args, **kwargs):
        # Auto-update line total before save
        self.line_total = self.sale_price * self.quantity
        super().save(*args, **kwargs)

pos_system/sales/forms.py
from django import forms
from .models import SalesOrder
from customer.models import Customer

class SalesOrderForm(forms.ModelForm):
    class Meta:
        model = SalesOrder
        fields = ['customer', 'notes']
        widgets = {
            'customer': forms.Select(attrs={'class': 'form-control'}),
            'notes': forms.Textarea(attrs={'rows': 3, 'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['customer'].queryset = Customer.objects.all()

pos_system/sales/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.contrib import messages
from .models import SalesOrder, SalesOrderItem
from .forms import SalesOrderForm
from products.models import Product

# Create your views here.

class SalesListView(LoginRequiredMixin, ListView):
    model = SalesOrder
    template_name = 'sales/sales_list.html'
    context_object_name = 'sales_orders'
    paginate_by = 150

    def get_queryset(self):
        query = self.request.GET.get("sale-search", "")
        sales = SalesOrder.objects.all().order_by('-created_at').prefetch_related('sales_items')

        if query:
            sales = sales.filter(
                Q(status__contains=query) |
                Q(order_id__icontains=query) |
                Q(invoice_number__icontains=query) |
                Q(customer__name__icontains=query)
            )
        return sales

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_query"] = self.request.GET.get("sale-search", "")
        return context
        


class SalesOrderFormView(LoginRequiredMixin, CreateView):
    model = SalesOrder
    template_name = 'sales/sales_form.html'
    form_class = SalesOrderForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        response = super().form_valid(form)
        order_id = self.object.order_id
        messages.success(self.request, f"Sales Order with {order_id} has been created.")
        return response
    
    def get_success_url(self):
        return reverse_lazy("sales:create_sales_order_items", kwargs={'pk': self.object.pk})

class SalesOrderItemsFormView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        order_id = kwargs.get('pk')
        order = get_object_or_404(SalesOrder, pk=order_id)
        products = Product.objects.all()
        return render(request, "sales/sales_items_form.html", {'order':order, 'products':products})
    
    def post(self, request, *args, **kwargs):
        order_id = kwargs.get('pk')
        order = get_object_or_404(SalesOrder, pk=order_id)
        product = request.POST.getlist("product[]")
        quantity = request.POST.getlist("quantity[]")
        discount = request.POST.get("discount")
        final_total = request.POST.get("final_total")

        # print(order_id)
        # print(order.order_id)
        # print(product)
        # print(quantity)
        # print(gand_total)
        # print(discount)
        # print(final_total)

        valid_items = {}
        for p, qty in zip(product, quantity):
            if not p or not qty:
                continue
            q = int(qty)
            if p in valid_items:
                valid_items[p] += q
            else:
                valid_items[p] = q
        print(valid_items)


        bulk_items = []
        for p_id, qty in valid_items.items():
            print(p_id, qty)
            product = Product.objects.get(pk=p_id)
            
            bulk_items.append(
                SalesOrderItem(
                    sales_order=order,
                    product=product,
                    quantity=qty,
                    sale_price=product.sale_price,
                    line_total=product.sale_price * qty
                    )
            )

        for pr, qty in valid_items.items():
            if not pr or not qty:
                continue
            product = Product.objects.get(pk=pr)
            product.quantity -= qty
            product.save(update_fields=['quantity'])

        if bulk_items:
            SalesOrderItem.objects.bulk_create(bulk_items)

        total = sum(item.line_total for item in bulk_items)
        order.subtotal += total
        order.discount = discount
        order.total_amount = final_total
        order.save(update_fields=['subtotal', 'discount', 'total_amount'])
        order.update_customer_balance()
        messages.success(request, f"Items Added for Sales Order {order.order_id}")

        url = reverse("payments:payment_form_view")
        query = f"?sale_order={order_id}&customer={order.customer.id}"
        return redirect(url + query)



class SalesOrderDetailView(LoginRequiredMixin, DetailView):
    model = SalesOrder
    template_name = 'sales/sales_details.html'
    context_object_name = 'order'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["items"] = self.object.sales_items.select_related("product")
        return context


# AJAX view to get product details by barcode
def product_by_barcode(request):
    
    barcode = request.GET.get("barcode", "")
    print(barcode)

    try:
        product = Product.objects.get(barcode=barcode)
        return JsonResponse({
            "id": product.id,
            "name": product.product_name,
            "sale_price": str(product.sale_price),
            "stock": product.quantity,
        })
    except Product.DoesNotExist:
        return JsonResponse({"error": "Product not found"}, status=404)

pos_system/sales/templates/sales/sales_details.html
{% extends "dashboard_base.html" %}

{% block title %}Purchase Order Items View{% endblock title %}

{% block extra_css %}

.main-container {
    padding: 30px 50px;
}

.header-bar {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-bottom: 20px;
}

.btn-back {
    background: #0284c7;
    color: #fff;
    padding: 6px 12px;
    text-decoration: none;
    border-radius: 5px;
    transition: 0.2s;
}
.btn-back:hover {
    background: #0369a1;
}

.order-info-box {
    background: #f9f9f9;
    border: 1px solid #ddd;
    border-radius: 8px;
    padding: 15px 20px;
    margin-bottom: 25px;
}

.order-meta p {
    margin: 6px 0;
    font-size: 15px;
}

.status {
    padding: 2px 8px;
    border-radius: 4px;
    font-size: 13px;
    color: #fff;
}
.status.paid { background: #ff0000ff; }
.status.partial { background: #28a745; }
.status.unpaid { background: #f0ad4e; }

.section-title {
    margin: 15px 0 10px;
    font-size: 18px;
}

.data-table {
    width: 100%;
    border-collapse: collapse;
    background: #fff;
}
.data-table th, .data-table td {
    border: 1px solid #ddd;
    padding: 8px 10px;
    text-align: left;
}
.data-table th {
    background: #efefef;
    font-weight: bold;
}
.no-data {
    text-align: center;
    color: #777;
    padding: 15px 0;
}

{% endblock extra_css %}


{% block content %}

<div class="main-container">


    <a href="{% url 'sales:sales_list_view' %}" class="btn-back"><< Back</a>
    <div class="header-bar">
        <h2>Sales Order Details</h2>
    </div>

    <div class="order-info-box">
        <div class="order-meta">
            <p><strong>Order ID:</strong> {{ order.order_id }}</p>
            <p><strong>Invoice Number:</strong> {{ order.invoice_number }}</p>
            <p><strong>Customer:</strong> {{ order.customer.name }}</p>
            <p><strong>Sales Date:</strong> {{ order.sale_date }}</p>
            <p><strong>Created By:</strong> {{ order.created_by }}</p>
            <p><strong>Grand Total:</strong> Rs. {{ order.subtotal }}</p>
            <p><strong>Discount:</strong> Rs. {{ order.discount }}</p>
            <p><strong>Final Total:</strong> Rs. {{ order.total_amount }}</p>
            <p><strong>Paid Amount:</strong> Rs. {{ order.paid_amount }}</p>
            <p><strong>Remaining Amount:</strong> Rs. {{ order.remaining_amount }}</p>
            <p><strong>Notes:</strong> {{ order.notes|default:"—" }}</p>
            <p><strong>Status:</strong>
                {% if order.status == 'Paid' %}
                    <span class="status paid">Paid</span>
                {% elif order.status == 'Partial' %}
                    <span class="status partial">Partially Paid</span>
                {% else %}
                    <span class="status unpaid">Unpaid</span>
                {% endif %}
            </p>
        </div>
    </div>

    <h3 class="section-title">Purchased Items</h3>
    <table class="data-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Product</th>
                <th>Sale Price</th>
                <th>Quantity</th>
                <th>Line Total</th>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.product.product_name }}</td>
                <td>Rs. {{ item.sale_price }}</td>
                <td>{{ item.quantity }}</td>
                <td>Rs. {{ item.line_total }}</td>
            </tr>
            {% empty %}
            <tr><td colspan="5" class="no-data">No items found for this order.</td></tr>
            {% endfor %}
        </tbody>
    </table>

</div>

{% endblock content %}

pos_system/sales/templates/sales/sales_form.html
{% extends "dashboard_base.html" %}

{% block title %}Purchase Order Form{% endblock title %}

{% block extra_css %}
.page-header {
display: flex;
justify-content: center;
align-items: center;
margin-top: 20px;
}
.page-header h2 {
color: #024f83;
font-size: 1.8rem;
}
.purchase-form-card {
background: #fff;
padding: 25px;
border-radius: 10px;
box-shadow: 0 0 5px rgba(0,0,0,0.1);
width: 400px;
margin: 0 auto;
}

.purchase-form-card select,
.purchase-form-card textarea {
width: 100%;
padding: 10px;
margin-top: 10px;
border: 1px solid #ccc;
border-radius: 6px;
font-size: 1rem;
}

.popup-overlay {
position: fixed;
inset: 0;
background: rgba(0,0,0,0.4);
display: flex;
align-items: center;
justify-content: center;
animation: fadeIn 0.3s ease-in-out;
}

.popup-card {
background: white;
padding: 25px 35px;
border-radius: 12px;
text-align: center;
box-shadow: 0 2px 10px rgba(0,0,0,0.2);
animation: slideIn 0.4s ease;
}

.ok-btn {
background: #28a745;
color: white;
border: none;
padding: 8px 20px;
margin-top: 15px;
border-radius: 6px;
cursor: pointer;
}
.add-btn {
width: 100%;
background: #0284c7;
border: none;
color: #fff;
padding: 10px 15px;
border-radius: 6px;
cursor: pointer;
transition: background 0.3s;
}

.add-btn:hover {
background: #0369a1;
}

.ok-btn:hover {
background: #218838;
}

.back-btn-container {
margin: 10px 50px;
}
.back-btn {
background: #0284c7;
border: none;
color: #fff;
padding: 6px 15px;
border-radius: 6px;
cursor: pointer;
font-size: 15px;
text-decoration: none;
transition: background 0.3s;
}
.back-btn:hover {
background: #0369a1;
}


{% endblock %}

{% block content %}

<div class="back-btn-container">
        <a href="{% url 'sales:sales_list_view' %}" class="back-btn"> << Back</a>
</div>

{% if messages %}
    {% for message in messages %}
    <div style="
            width: 40%;
            
            background-color: rgba(40, 167, 69, 0.15);
            color: #155724;
            border: 1px solid rgba(40, 167, 69, 0.3);
            border-radius: 5px;
            padding: 12px 18px;
            margin-bottom: 15px;
            position: relative;
            left: 400px;
            box-sizing: border-box;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        ">
        <span>{{ message }}</span>
        <button type="button" onclick="this.parentElement.style.display='none'" style="
                position: absolute;
                top: 8px;
                right: 12px;
                background: none;
                border: none;
                font-size: 18px;
                color: #155724;
                cursor: pointer;
                font-weight: bold;
            ">&times;</button>
    </div>
    {% endfor %}
    {% endif %}


<div class="page-header">
    <h2>Create Sale Order</h2>
</div>

<div class="purchase-form-card">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="add-btn">Create Sale Order</button>
    </form>
</div>

{% endblock %}

pos_system/sales/templates/sales/sales_list.html
{% extends "dashboard_base.html" %}

{% block title %}Product List{% endblock title %}

{% block extra_css %}
.container {
max-width: 1250px;
margin: 30px auto;
padding: 0 15px;
}

.page-header {
display: flex;
justify-content: space-between;
align-items: center;
margin-bottom: 20px;
}

.page-header h2 {
color: #024f83;
font-size: 1.8rem;
margin: 0;
}

.back-btn {
background: #0284c7;
border: none;
color: #fff;
padding: 6px 15px;
border-radius: 6px;
cursor: pointer;
font-size: 15px;
text-decoration: none;
transition: background 0.3s;
}
.back-btn:hover {
background: #0369a1;
}
.search-bar {
display: flex;
justify-content: space-between;
gap: 10px;
margin-bottom: 20px;
}

.search-bar div{
display: flex;
align-items: center;
justify-content: end;
gap: 3px;
width: 500px;
}
.search-bar input {
flex: 1;
max-width: 300px;
padding: 10px;
border: 1px solid #ccc;
border-radius: 6px;
}

.search-bar button {
background: #0284c7;
border: none;
color: #fff;
padding: 10px 15px;
border-radius: 6px;
cursor: pointer;
}

.product-table {
width: 100%;
border-collapse: collapse;
background: #fff;
border-radius: 8px;
overflow: hidden;
box-shadow: 0 2px 6px rgba(0,0,0,0.1);
}

.product-table th, .product-table td {
padding: 12px 15px;
text-align: center;
border-bottom: 1px solid #ddd;
}

.product-table th {
background: #0284c7;
color: white;
font-weight: normal;
}

.product-table tr:hover {
background: #f1f9ff;
}

.actions {
display: flex;
justify-content: center;
gap: 5px;
}

.action-btn {
border: none;
background: none;
cursor: pointer;
font-size: 16px;
text-decoration: none;
}

.view {
background: #00e9faff;
}

.delete {
background: #ff5959ff;
}

.status {
padding: 2px 8px;
border-radius: 4px;
font-size: 13px;
color: #fff;
}
.status.paid { background: #ff0000ff; }
.status.partial { background: #28a745; }
.status.unpaid { background: #f0ad4e; }

.no-products {
text-align: center;
padding: 20px;
color: #555;
font-style: italic;
}

.pagination-container {
display: flex;
justify-content: center;
margin: 20px 0px;
}

.pagination {
list-style: none;
display: flex;
gap: 0.3rem;
padding: 0;
margin: 0;
}

.pagination li {
padding: 0.5rem 0.7rem;
background: #38bdf8;
color: white;
border-radius: 6px;
font-size: 13px;
cursor: pointer;
transition: 0.2s;
}

.pagination li a {
color: white;
text-decoration: none;
}

.pagination li:hover {
background: #0ea5e9;
}

.pagination .disabled {
background: #94a3b8;
cursor: not-allowed;
}

.pagination .active {
background: #facc15;
color: #0f172a;
font-weight: bold;
}


/* Overlay */
.modal {
position: fixed;
top: 0; left: 0;
width: 100%; height: 100%;
display: none;
justify-content: center;
align-items: center;
background: rgba(0,0,0,0.4);
z-index: 999;
animation: fadeIn 0.3s ease-in-out;
}

/* Show modal when targeted */
.modal:target {
display: flex;
}

/* Modal box */
.modal-content {
background: #fff;
padding: 25px;
border-radius: 10px;
text-align: center;
width: 90%;
max-width: 380px;
box-shadow: 0 3px 10px rgba(0,0,0,0.2);
animation: scaleUp 0.3s ease-in-out;
}

/* Buttons */
.modal-actions {
display: flex;
justify-content: space-around;
margin-top: 20px;
}

.confirm-btn {
background: #dc2626;
color: #fff;
border: none;
padding: 10px 18px;
border-radius: 6px;
cursor: pointer;
transition: background 0.3s;
}

.confirm-btn:hover {
background: #b91c1c;
}

.cancel-btn {
background: #0284c7;
color: #fff;
padding: 10px 18px;
border-radius: 6px;
text-decoration: none;
transition: background 0.3s;
}

.cancel-btn:hover {
background: #0369a1;
}

/* Animations */
@keyframes fadeIn {
from { opacity: 0; }
to { opacity: 1; }
}

@keyframes scaleUp {
from { transform: scale(0.9); opacity: 0; }
to { transform: scale(1); opacity: 1; }
}

/* Responsive */
@media (max-width: 768px) {
.product-table th, .product-table td {
padding: 8px;
font-size: 14px;
}
.search-bar {
flex-direction: column;
align-items: stretch;
}
.search-bar input {
max-width: 100%;
}
}
{% endblock %}

{% block content %}
<div class="container">
    <div class="page-header">
        <h2>All Sales</h2>
    </div>

    <div class="search-bar">
        <a href="{% url 'sales:create_sales_order' %}" class="back-btn">+ Add New Sale</a>
        <form>
            <div>
                <input type="text" name="sale-search" placeholder="Search by Order-ID / Invoice / Customer / Status">
                <button type="submit">Search</button>
            </div>
        </form>
    </div>

    <div class="pagination-container">
        <ul class="pagination">

            {% if page_obj.has_previous %}
            <li><a href="?page=1{% if search_query %}&sale-search={{ search_query }}{% endif %}">&laquo; First</a></li>
            <li><a
                    href="?page={{ page_obj.previous_page_number }}{% if search_query %}&sale-search={{ search_query }}{% endif %}">&lsaquo;
                    Prev</a></li>
            {% else %}
            <li class="disabled">&laquo; First</li>
            <li class="disabled">&lsaquo; Prev</li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
            <li class="active">{{ num }}</li>
            {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %} <li><a
                    href="?page={{ num }}{% if search_query %}&sale-search={{ search_query }}{% endif %}">{{ num }}</a>
                </li>
                {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                <li><a
                        href="?page={{ page_obj.next_page_number }}{% if search_query %}&sale-search={{ search_query }}{% endif %}">Next
                        &rsaquo;</a></li>
                <li><a
                        href="?page={{ page_obj.paginator.num_pages }}{% if search_query %}&sale-search={{ search_query }}{% endif %}">Last
                        &raquo;</a></li>
                {% else %}
                <li class="disabled">Next &rsaquo;</li>
                <li class="disabled">Last &raquo;</li>
                {% endif %}

        </ul>
    </div>


    <table class="product-table">
        <thead>
            <tr>
                <th>#</th>
                <th>Sale-ID</th>
                <th>Customer</th>
                <th>Invoice-No</th>
                <th>Date</th>
                <th>Total Items</th>
                <th>Total Amount</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% if sales_orders %}
            {% for sale in sales_orders %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ sale.order_id }}</td>
                <td>{{ sale.customer.name }}</td>
                <td>{{ sale.invoice_number }}</td>
                <td>{{ sale.created_at|date:"d M Y" }}</td>
                <td>{{ sale.sales_items.count }}</td>
                <td>{{ sale.total_amount }}</td>
                <td>
                    {% if sale.status == 'Paid' %}
                    <span class="status paid">Paid</span>
                    {% elif sale.status == 'Partial' %}
                    <span class="status partial">Partial</span>
                    {% else %}
                    <span class="status unpaid">Unpaid</span>
                    {% endif %}
                </td>
                <td>
                    <div class="actions">
                        <a class="action-btn view" title="Edit" href="{% url 'sales:sales_detail_view' sale.pk %}">
                            🔍
                        </a>
                        <!-- Delete icon link -->
                        <!-- <a href="#delete-{{ sale.pk }}" class="action-btn delete">🗑️</a> -->

                        <!-- Modal Box -->
                        <!-- <div id="delete-{{ sale.pk }}" class="modal">
                            <div class="modal-content">
                                <h3>Confirm Deletion</h3>
                                <p>Are you sure you want to delete <strong>{{ sale.pk }}</strong>?</p>
                                <div class="modal-actions">
                                    <form method="post" action="">
                                        {% csrf_token %}
                                        <button type="submit" class="confirm-btn">Yes, Delete</button>
                                    </form>
                                    <a href="#" class="cancel-btn">Cancel</a>
                                </div>
                            </div>
                        </div> -->

                    </div>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="9" class="no-products">No Sales available</td>
            </tr>
            {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}